stages:
  - test
  - release

test:
  image: hacksawgaming/hacksaw-build:4.0.0-rc.2-7
  stage: test
  before_script:
    - yarn
  script:
    - npm test
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+\.\d+\.\d+(?:-rc\.[0-9]+)?/

package_release:
  image: hacksawgaming/hacksaw-build:4.0.0-rc.2-7
  stage: release
  before_script:
    - yarn
  script:
    - npx @hacksawstudios/gitlab-ci-releaser --npm
  only:
    refs:
      - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+\.\d+\.\d+/ 

package_rc:
  image: hacksawgaming/hacksaw-build:4.0.0-rc.2-7
  stage: release
  before_script:
    - yarn
  script:
    - npx @hacksawstudios/gitlab-ci-releaser --npm --preid rc
  only:
    - develop
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+\.\d+\.\d+(?:-rc\.[0-9]+)?/
