stages:
  - test
  - release

test:
  image: hacksawgaming/hacksaw-build:4.0.0-preview.5
  stage: test
  before_script:
    - npm i --unsafe-perm
  script:
    - npm test

package_release:
  image: hacksawgaming/hacksaw-build:4.0.0-preview.5
  stage: release
  before_script:
    - apk add --update zip
    - npm i
  script:
    - $(npm bin)/gitlab-ci-releaser --npm
  only:
    - master

package_rc:
  image: hacksawgaming/hacksaw-build:4.0.0-preview.5
  stage: release
  before_script:
    - apk add --update zip
    - npm i
  script:
    - $(npm bin)/gitlab-ci-releaser --npm --preid rc
  only:
    - develop
