stages:
  - test
  - release

test:
  image: hacksawgaming/hacksaw-build
  stage: test
  before_script:
    - npm i
  script:
    - haxelib run travix node

package_release:
  image: hacksawgaming/hacksaw-build
  stage: release
  before_script:
    - npm i
  script:
    - $(npm bin)/gitlab-ci-releaser --npm
  only:
    - master

package_rc:
  image: hacksawgaming/hacksaw-build
  stage: release
  before_script:
    - npm i
  script:
    - $(npm bin)/gitlab-ci-releaser --npm --preid rc
  only:
    - develop
