language: haxe
haxe:
  - "3.2.1"
  - development
install:
  - haxelib dev src $TRAVIS_BUILD_DIR
  - haxelib install munit
  - haxelib list

script:
  - haxe test.hxml

cache:
  directories:
    - $HOME/haxe/lib